# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Copypasta < Formula
  desc "Clean dark-themed website text for pasting into Outlook/Word"
  homepage "https://github.com/guigui42/copypasta"
  version "1.0.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/guigui42/copypasta/releases/download/v1.0.0/copypasta_darwin_amd64.tar.gz"
    sha256 "d013256a03f2187dac4ab9e3e170d3981a1f88ca1ff94db017ed9c1720e2a9e8"

    define_method(:install) do
      bin.install "copypasta"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/guigui42/copypasta/releases/download/v1.0.0/copypasta_darwin_arm64.tar.gz"
    sha256 "b59a01d79683c181dbbb4e3da03f64a60335beb4977e6c8f5ff024008d4e9f2d"

    define_method(:install) do
      bin.install "copypasta"
    end
  end
end
