# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Copypasta < Formula
  desc "Clean dark-themed website text for pasting into Outlook/Word"
  homepage "https://github.com/guigui42/copypasta"
  version "1.0.2"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/guigui42/copypasta/releases/download/v1.0.2/copypasta_darwin_amd64.tar.gz"
    sha256 "d1693aa3659fd148bfb796037b89403a6f33756e94ff5c627d18abb37e3bec54"

    define_method(:install) do
      bin.install "copypasta"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/guigui42/copypasta/releases/download/v1.0.2/copypasta_darwin_arm64.tar.gz"
    sha256 "1efacee0a60853a34fa25a189b8ee6d8bd98d93c71bbcc1d0d6d30acefebb59c"

    define_method(:install) do
      bin.install "copypasta"
    end
  end
end
