# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Customerpromptgenerator < Formula
  desc "Customer prompt generator"
  homepage "https://github.com/guigui42/CustomerPromptGenerator"
  version "1.0.2"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/guigui42/CustomerPromptGenerator/releases/download/v1.0.2/CustomerPromptGenerator_darwin_amd64.tar.gz"
    sha256 "d650fdd9eba9b9a5bcd8d4fd2bf66227311333aac8b99fff15897c5e2c0b6fff"

    define_method(:install) do
      bin.install "customerpromptgenerator"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/guigui42/CustomerPromptGenerator/releases/download/v1.0.2/CustomerPromptGenerator_darwin_arm64.tar.gz"
    sha256 "323abfa7fd9f3c2615a045aeed31efb0a468ce1c5b33aac7e50393949c4a26fc"

    define_method(:install) do
      bin.install "customerpromptgenerator"
    end
  end
end
