# typed: false
# frozen_string_literal: true

# This file was generated by GitHub Copilot. DO NOT EDIT.
class Customerpromptgenerator < Formula
  desc "Customer prompt generator"
  homepage "https://github.com/guigui42/CustomerPromptGenerator"
  version "1.0.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/guigui42/homebrew-tap/releases/download/v1.0.0/customerpromptgenerator_darwin_amd64.tar.gz"
    sha256 "45dcec39043dbd04fe10f23af429d17ce68bbed88b1cdacd805853282e9e30da"

    define_method(:install) do
      bin.install "customerpromptgenerator/customerpromptgenerator"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/guigui42/homebrew-tap/releases/download/v1.0.0/customerpromptgenerator_darwin_arm64.tar.gz"
    sha256 "ce4a4bb0bbcd23ba2c3cec244c2b66456bfe967f356e4bfb1bcb00a0bf74395d"

    define_method(:install) do
      bin.install "customerpromptgenerator/customerpromptgenerator"
    end
  end
end
